vim.o.path = '**'
vim.g.mapleader = ' '
vim.g.maplocalleader = ' '
vim.g.have_nerd_font = false
vim.o.number = true
vim.o.numberwidth = 2
vim.o.ruler = false
vim.o.relativenumber = true
vim.o.mouse = ''
vim.o.showmode = false
vim.o.breakindent = true
vim.o.undofile = true
vim.o.ignorecase = true
vim.o.smartcase = true
vim.o.signcolumn = 'yes'
vim.o.updatetime = 250
vim.o.timeoutlen = 300
vim.o.splitright = true
vim.o.splitbelow = true
vim.o.list = true
vim.opt.listchars = { tab = '» ', trail = '·', nbsp = '␣' }
vim.o.inccommand = 'split'
vim.o.cursorline = false
vim.o.scrolloff = 10
vim.o.confirm = true
vim.opt.tabstop = 4
vim.opt.shiftwidth = 4
vim.opt.softtabstop = 4
vim.opt.expandtab = true
vim.opt.autoread = true
vim.opt.selection = 'inclusive'
vim.opt.encoding = 'utf-8'
vim.opt.fileencoding = 'utf-8'
vim.g.mkdp_preview_options = {
  katex = {},
}
vim.opt.wrap = true
vim.opt.linebreak = true
vim.o.conceallevel = 2
vim.opt.guicursor = 'n-c:block-blinkon500-blinkoff500,' .. 'i-ci:ver25-blinkon500-blinkoff500,' .. 'v-ve:block,' .. 'r-cr:hor20,' .. 'o:hor50'
